# Generated by Django 3.2.12 on 2022-02-08 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRegionParameters',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('last_updated_on_MONCIL', models.DateTimeField(blank=True, null=True)),
                ('last_updated_in_db', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'WeatherRegionParameters',
                'db_table': 'WeatherRegionParameters',
                'unique_together': {('region', 'parameter', 'order', 'last_updated_on_MONCIL')},
            },
        ),
        migrations.CreateModel(
            name='YearWiseWeatherInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jan', models.FloatField(blank=True, null=True)),
                ('feb', models.FloatField(blank=True, null=True)),
                ('mar', models.FloatField(blank=True, null=True)),
                ('apr', models.FloatField(blank=True, null=True)),
                ('may', models.FloatField(blank=True, null=True)),
                ('jun', models.FloatField(blank=True, null=True)),
                ('jul', models.FloatField(blank=True, null=True)),
                ('aug', models.FloatField(blank=True, null=True)),
                ('sep', models.FloatField(blank=True, null=True)),
                ('oct', models.FloatField(blank=True, null=True)),
                ('nov', models.FloatField(blank=True, null=True)),
                ('dec', models.FloatField(blank=True, null=True)),
                ('win', models.FloatField(blank=True, null=True)),
                ('spr', models.FloatField(blank=True, null=True)),
                ('sum', models.FloatField(blank=True, null=True)),
                ('aut', models.FloatField(blank=True, null=True)),
                ('ann', models.FloatField(blank=True, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('weather', models.ForeignKey(db_column='weather', on_delete=django.db.models.deletion.CASCADE, to='weatherapp.weatherregionparameters')),
            ],
            options={
                'verbose_name_plural': 'Year_Wise_Weather_Info',
                'db_table': 'YearWiseWeatherInfo',
            },
        ),
        migrations.CreateModel(
            name='RankWiseWeatherInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jan', models.FloatField(blank=True, null=True)),
                ('feb', models.FloatField(blank=True, null=True)),
                ('mar', models.FloatField(blank=True, null=True)),
                ('apr', models.FloatField(blank=True, null=True)),
                ('may', models.FloatField(blank=True, null=True)),
                ('jun', models.FloatField(blank=True, null=True)),
                ('jul', models.FloatField(blank=True, null=True)),
                ('aug', models.FloatField(blank=True, null=True)),
                ('sep', models.FloatField(blank=True, null=True)),
                ('oct', models.FloatField(blank=True, null=True)),
                ('nov', models.FloatField(blank=True, null=True)),
                ('dec', models.FloatField(blank=True, null=True)),
                ('win', models.FloatField(blank=True, null=True)),
                ('spr', models.FloatField(blank=True, null=True)),
                ('sum', models.FloatField(blank=True, null=True)),
                ('aut', models.FloatField(blank=True, null=True)),
                ('ann', models.FloatField(blank=True, null=True)),
                ('jan_year', models.DateField(blank=True, null=True)),
                ('feb_year', models.DateField(blank=True, null=True)),
                ('mar_year', models.DateField(blank=True, null=True)),
                ('apr_year', models.DateField(blank=True, null=True)),
                ('may_year', models.DateField(blank=True, null=True)),
                ('jun_year', models.DateField(blank=True, null=True)),
                ('jul_year', models.DateField(blank=True, null=True)),
                ('aug_year', models.DateField(blank=True, null=True)),
                ('sep_year', models.DateField(blank=True, null=True)),
                ('oct_year', models.DateField(blank=True, null=True)),
                ('nov_year', models.DateField(blank=True, null=True)),
                ('dec_year', models.DateField(blank=True, null=True)),
                ('win_year', models.DateField(blank=True, null=True)),
                ('spr_year', models.DateField(blank=True, null=True)),
                ('sum_year', models.DateField(blank=True, null=True)),
                ('aut_year', models.DateField(blank=True, null=True)),
                ('ann_year', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('weather', models.ForeignKey(db_column='weather', on_delete=django.db.models.deletion.CASCADE, to='weatherapp.weatherregionparameters')),
            ],
            options={
                'verbose_name_plural': 'Rank_Wise_Weather_Info',
                'db_table': 'RankWiseWeatherInfo',
            },
        ),
    ]
